### ISSUE TITLE
Hypercorn never propagates exception from asgi app using trio

### ISSUE THREAD

**Issue by artgromov** [pgjones/hypercorn#31]
Hypercorn doesn't follow trio's rule that exceptions must always propagate:
https://trio.readthedocs.io/en/stable/design.html#exceptions-always-propagate

It seems that trio support should also mean support of trio's ideology.

code given:
```
import trio
from functools import partial
from hypercorn.trio import serve
from hypercorn.config import Config


async def app(scope, receive, send):
    raise KeyError('bla')


if __name__ == '__main__':
    config = Config()
    config.bind = [':::8080']

    trio.run(partial(serve, app, config))

```

requests made:
```
curl localhost:8080
curl localhost:8080
```

output:
```
2020-06-06 16:38:23,468 DEBUG    logbroker.automation args: Namespace(address='::', port=8080)
ASGI Framework Lifespan error, continuing without Lifespan support
Traceback (most recent call last):
  File "contrib/python/Hypercorn/hypercorn/trio/lifespan.py", line 29, in handle_lifespan
    await invoke_asgi(self.app, scope, self.asgi_receive, self.asgi_send)
  File "contrib/python/Hypercorn/hypercorn/utils.py", line 203, in invoke_asgi
    await app(scope, receive, send)
  File "logbroker/automation/__init__.py", line 47, in app
    raise KeyError('bla')
KeyError: 'bla'
Running on [::]:8080 over http (CTRL + C to quit)
Error in ASGI Framework
Traceback (most recent call last):
  File "contrib/python/Hypercorn/hypercorn/trio/spawn_app.py", line 14, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "contrib/python/Hypercorn/hypercorn/utils.py", line 203, in invoke_asgi
    await app(scope, receive, send)
  File "logbroker/automation/__init__.py", line 47, in app
    raise KeyError('bla')
KeyError: 'bla'
Error in ASGI Framework
Traceback (most recent call last):
  File "contrib/python/Hypercorn/hypercorn/trio/spawn_app.py", line 14, in _handle
    await invoke_asgi(app, scope, receive, send)
  File "contrib/python/Hypercorn/hypercorn/utils.py", line 203, in invoke_asgi
    await app(scope, receive, send)
  File "logbroker/automation/__init__.py", line 47, in app
    raise KeyError('bla')
KeyError: 'bla'
```
And server is still running after all, but it shouldn't.
Trio's ideology forces user to make error processing explicit. Hypercorn implicitly drops such errors for it's users.

Why https://github.com/pgjones/hypercorn/blob/master/src/hypercorn/trio/tcp_server.py#L80 ?

**Comment by pgjones** [comment]
Hypercorn takes the view that an error by the ASGI app is a server error that it should handle by returning a 500 response to the client (if it can otherwise it closes the connection). I'm not sure what could be gained by having the server crash? 

Note that you can add explicit error handling by wrapping the `app`,

```python
async def wrapper_app(scope, receive, send):
    try:
        await app(scope, receive, send)
    except ?:
        # Do something 
```

**Comment by zoranbosnjak** [comment]
@pgjones  I am struggling with exactly the same problem for a few days now. I would appreciate your suggestion.

> I'm not sure what could be gained by having the server crash?

Crashing the server in case of unhandled exceptions makes a lot of sense. It means "give up" if something unexpected happens (that is: something that was not anticipated). The web server is normally started by some process supervisor (like upstart, systemd...). The process could be restarted by external supervisor as an obvious benefit. If the server does not crash, the problem is not detected and the process remains in a degraded state.

Could you please suggest how to make it crash with the `app_wrapper` or with any other workaround? In particular:
- How to specify to catch **ALL** exceptions, except regular termination (CTRL-C)?
- How to actually stop (crash) the server in `# Do something` block above, since re-rising the exception won't work?

My test program looks like this

```
# src/test3.py
from quart_trio import QuartTrio

app = QuartTrio(__name__)

async def background_task():
    raise Exception('testing...')

@app.route('/')
async def hello():
    return 'hello'

@app.before_serving
async def startup():
    app.add_background_task(background_task)

if __name__ == '__main__':
    app.run()
```

Expected behaviour is that program crashes, but it hangs instead.

The problem of not propagating the exception is present in both cases below. So I belive the problem is in `quart-trio` too.

```bash
# run with hypercorn
hypercorn -k trio test3:app

# run in devel mode
python ./src/test3.py
```
